### ISSUE TITLE
Share ->Copy Link error: clipboard.copy is not a function

### ISSUE THREAD

**Issue by adrianandrasescu** [ONLYOFFICE/onlyoffice-humhub#1]
HumHub version: 1.3.13
OnlyOffice module version: 1.0.2

When I use button COPY LINK in Document editor , Share modal popup I have the js error:
"clipboard.copy is not a function"

in order to work I had to replace "clipboard.copy" with "clipboard.writeText" in 
/onlydocuments/widgets/views/share.php

Thank you for update.

**Comment by Eloncase** [comment]
Hello!
Thanks for your contribution!
