### ISSUE TITLE
OnlyOffice shows outdated file content when file was overwritten in HumHub

### ISSUE THREAD

**Issue by pheraph** [ONLYOFFICE/onlyoffice-humhub#104]
When editing a HumHub file in OnlyOffice, later downloading and editing it locally and uploading it again, overwriting the file with the same name in Humhub, OnlyOffice continues to show the old file content. If one downloads the file from Humhub, the correct newer content is included. To complicate matters further, updating a file seems to work exactly once after all. All subsequent attempts fail and OnlyOffice only displays the old version.

Since apparently the error occurs when passing to OnlyOffice, I have created the issue here, as HumHub has the correct file, but OnlyOffice doesn't. Maybe @luke- can confirm that this is the right place for it.

I have created a screen recording where the error can be observed. I can reproduce the error on two HumHub instances (but they are coupled to the same OnlyOffice instance): https://seafile.rlp.net/f/1cc355cce99a408dbc6b

**Comment by dreua** [comment]
Can you provide the versions of HumHub and the only office plugin, maybe also of the document server?
Wondering  whether that is a regression or just a rare use case that no one noticed or bothered to report.
I shall try that on my instance if I find the time.

**Comment by pheraph** [comment]
Thank you, these are the versions:

````
HumHub: 1.14.3
OnlyOffice-Connector: 3.0.0
OnlyOffice: 7.1.1
````

**Comment by dreua** [comment]
I can confirm that OnlyOffice is unaware of the new uploaded file. It seems that this is only an issue when using the cfiles plugin because otherwise I wouldn't know how to change a file in place. (Editing a post and uploading the changed file results in two files with the same name being attached to a post.)

HumHub: 1.14.4
Connector: 3.0.0
documentserver: 7.4.1.1
(Those should be all the latest versions at the time of writing.)

**Comment by pheraph** [comment]
I was also able to reproduce the issue on a humhub.com demo instance. Even though the error probably does not occur too often in real world conditions, we had it and it is serious imho. 

@luke- Is the issue correctly placed here or is it also related to other HumHub modules?

**Comment by luke-** [comment]
@pheraph We'll take a look into it... We recently fixed a similar problem with soft deleted files.
