### ISSUE TITLE
Opened documents can't be closed

### ISSUE THREAD

**Issue by lonesomewalker** [ONLYOFFICE/onlyoffice-humhub#116]
humhub: latest
documentserver: latest

Opening a document gives white page, the following error in browser console:

```
TypeError: Failed to fetch
at server/8.0.1-31/...ileType=docx:562:29
at Array.map (<anonymous>)
at Object.injactSvgIcons (server/8.0.1-31/...ileType=docx:561:27)
at i.createDelayedElements (server/8.0.1-31/...in/app.js:8:1531001)
at server/8.0.1-31/...in/app.js:8:2401849
```

**Comment by lonesomewalker** [comment]
Should this not be server/8.1.3 ...?

**Comment by lonesomewalker** [comment]
Okay, fixed this by deleting cache.
Now direct documents can be edited.

But shared links are still an issue.
Opening works, but clicking "close" only closes the file, but not the editor iframe :-/

**Comment by LinneyS** [comment]
Fixed 
bbff264001624dcc0f3d2a190ad5392c143b70d2

**Comment by lonesomewalker** [comment]
Well... the uploaded files now can be closed, but not shared/linked ones.

Is there another modal for this?

**Comment by lonesomewalker** [comment]
I mean:
if you click the button, the document gets closed, but the modal window is still shown, just without content.
But as i have seen, this should properly, right:

https://github.com/ONLYOFFICE/onlyoffice-humhub/blob/4b591ef52dd940c7836eca3de2cef35c051c36d6/resources/humhub.onlyoffice.js#L277-L288
