### ISSUE TITLE
Creating a new document fails on Humhub 1.16 & Documentserver 8.2

### ISSUE THREAD

**Issue by poVoq** [ONLYOFFICE/onlyoffice-humhub#117]
Edit: The creation of a new document fails. Editing ones that have been uploaded before works.

Installed from the official HumHub marketplace with a self-hosted Documentserver 8.2

The configuration says that the connection succeeded and it shows the correct version of the Document server there:

`ONLYOFFICE Docs successfully connected! - Installed version: 8.2.0.143
`

When trying to make a new .docx file it just fails with a:

```
An error occurred while handling your last action. (Handler not found).
onlyoffice.createSubmit
```

error in Humhub.

Thanks for the help!

**Comment by dreua** [comment]
Did it work before and stopped working with an update or is this happening right after installation?
Setup can be a bit tricky, I needed a few tries to get everything right between domains, reverse proxies etc. 

It currently works fine for me but I'm on the previous documentserver. (HumHub 1.16.2 / onlyoffice/documentserver:8.1.3.2)

**Comment by poVoq** [comment]
Right after installation, it is a fresh install.

**Comment by poVoq** [comment]
The same error happens with the official Demo server (also on 8.2), so I am guessing this module needs to be updated to work with a Documentserver v8.2 in general?

Or is there still something I might have to change on the Humhub side?

**Comment by dreua** [comment]
It is more likely just something wrong with your setup. You can always try with oo server 8.1 so be sure. Setup can be a bit tricky and the error messages are not always helpful. I can't help you any further here because first it has been a while since I set this up and second I have no clue about your setup.

**Comment by poVoq** [comment]
I followed the official guide to install Humhub.

I do have a bunch of other extensions installed from the official marketplace for testing, but those should not interfere with this one, or?

But I now figured out that if I upload a .docx in advance then this integration works as expected, what fails is the option from the HumHub menu to create a new file directly like this:
![image](https://github.com/user-attachments/assets/cc1d8445-fc3b-49a1-a089-0d7e1f8d7701)

**Comment by GeorgeONLYOFFICE** [comment]
Thanks for the explanation.

A few points to clarify

So when you click on 'Create document (Text, Spreadsheet, Presentation, Form template)', does the window with
format choices appear afterwards?

If it appears, suppose you click on 'Document' format, does the window 'Create document' appear where you are supposed
to enter the name of the document?

Does the issue finally appear when clicking on 'Save' button in the last window?

Additionaly, let us know if you tried to perform checks with a previous version of the Document Server and if the behavior had been the same.

**Comment by poVoq** [comment]
Ok, after some more testing I can't consistently replicate it. Sometimes it works, sometimes not.

I have the suspicion that it is related to changing the module settings and then not force updating the cache, i.e. if I do some setting change and afterwards force reload the page with ctrl+f5 it seems to work as expected.

Maybe the module needs to force invalidate the cache when changing the settings?

**Comment by GeorgeONLYOFFICE** [comment]
Hi thanks for specifying the details.
Could you provide some information regarding cache here, do you mean browser cache or the one on Humhub end?
Additionally, please specify which connector settings lead to the issue in your case, so that we could double check them for future reference.

**Comment by poVoq** [comment]
Both caches? Not sure. I mean if ctrl+f5 force reloading fixes it, it is probably a browser cache issue?

It doesn't really seem to matter which setting, but changing anything seems to cause the integration to fail until the page is force reloaded with ctrl+f5

**Comment by GeorgeONLYOFFICE** [comment]
Hi, we've managed to reproduce the behavior you mentioned and unfortunately, we cannot fix it on our side, since its the issue on Humhub's end. There is a following issue for your reference https://github.com/humhub/humhub/issues/2598

**Comment by dreua** [comment]
@GeorgeONLYOFFICE that issue is closed since 2017, maybe you pasted the wrong link?
