### ISSUE TITLE
File stream error with onlyoffice 2.1.3

### ISSUE THREAD

**Issue by niconacre** [ONLYOFFICE/onlyoffice-humhub#26]
Seems that's module ver 2.1.3 give an issue with stream
I used to have 2.1.3.2 install in selected instance without issue, but seems that's version not been available anymore

**Comment by ArchBlood** [comment]
The issue seems to be a missing php tag (i.e `<?php`) in the ViewFileHandler.php file on the uploaded version to the marketplace, it's shown in the repo however

https://github.com/ONLYOFFICE/onlyoffice-humhub/blob/d0a55add4756541a4c577723dbf537aa602fd880/filehandler/ViewFileHandler.php#L1
