### ISSUE TITLE
HumHub in Maintenance mode: The document could not be saved. Please check connection settings...

### ISSUE THREAD

**Issue by dreua** [ONLYOFFICE/onlyoffice-humhub#34]
![Screenshot_20210329_114522](https://user-images.githubusercontent.com/15114715/112824913-6a1be900-908b-11eb-8e7b-6cb7121f3a5e.png)

I have two nearly identical instances of Humhub which both use the same OnlyOffice document server container as back-end. Both worked without problems (one via HTTPS one HTTP previously) after upgrading the second (main) HumHub instance to 1.8.1 and HTTPS it can no longer save documents. (Viewing is fine, error message is shown right after document is opened.)

I'm in the process of figuring out the difference between those two instances and I'd like to document this in this bug for myself and maybe others struggling with this issue.

(OT: I'm up for hire, freelance, part time, full time. Solving issues like that and whatever Linux/OpenSource problems you may have. Email should be visible in my profile.)

**Comment by dreua** [comment]
HumHub's apache logs (request.log):
`"POST /index.php?r=onlyoffice%2Fbackend%2Ftrack&key=[redacted] HTTP/1.1" 302 11 "-" "Node.js/6.13"`

The Docker-DocumentServer logs in `/var/log/onlyoffice/documentserver/docservice/out.log` at the exact same second:
```
[ERROR] nodeJS - postData error: docId = [redacted] ;url = https:/[redacted]/index.php?r=onlyoffice%2Fbackend%2Ftrack&key=[redacted] ;data = {"key":"[redacted] ","status":1,"users":["[redacted] "],"actions":[{"type":1,"userid":"9[redacted] "}]}
Error: Error response: statusCode:302; headers:{"date":"Mon, 29 Mar 2021 12:19:40 GMT","server":"Apache/2.4.37 (centos) OpenSSL/1.1.1g","x-powered-by":"PHP/7.2.24","expires":"Thu, 19 Nov 1981 08:52:00 GMT","cache-control":"no-store, no-cache, must-revalidate","pragma":"no-cache","content-security-policy":"default-src *; connect-src  *; font-src 'self'; frame-src https://* http://* *; img-src https://* http://* * data:; object-src 'self'; script-src 'self' https://* http://* * 'unsafe-inline' 'report-sample'; style-src * https://* http://* * 'unsafe-inline';","x-content-security-policy":"default-src *; connect-src  *; font-src 'self'; frame-src https://* http://* *; img-src https://* http://* * data:; object-src 'self'; script-src 'self' https://* http://* * 'unsafe-inline' 'report-sample'; style-src * https://* http://* * 'unsafe-inline';","strict-transport-security":"max-age=31536000","x-xss-protection":"1; mode=block","x-content-type-options":"nosniff","referrer-policy":"no-referrer-when-downgrade","x-permitted-cross-domain-policies":"master-only","x-frame-options":"sameorigin","set-cookie":["PHPSESSID=v1jsma1sod2qjjor2nn8759gp7; path=/"],"location":"https://humhub-filmz-mainz.de/index.php?r=user%2Fauth%2Flogin","keep-alive":"timeout=5, max=100","connection":"Keep-Alive","transfer-encoding":"chunked","content-type":"application/json; charset=UTF-8"}; body:
{"error":0}
    at Request._callback (/snapshot/server/build/server/Common/sources/utils.js:0:0)
    at Request.init.self.callback (/snapshot/server/build/server/Common/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

Interesting: the URL starts with HTTPS but the call goes out via HTTP

**Comment by dreua** [comment]
Turned out there was a rather significant difference between the two Humhub instances: The latter had maintenance mode activated :see_no_evil: 

IMHO this needs to be
- [ ] Documented or fixed. Ideally OnlyOffice would be working in Mainenance mode as well.
- [ ] Made easier to debug. E.g. by checking the callback in the Plugin configuration and printing some information of what happened and what could have gone wrong.

**Comment by AtriLahiji** [comment]
Seems to still happen for my instance here. We are on the latest versions of both apps. Both use HTTPS only, and ONLYOFFICE seems to not think its getting a JWT???

Interestingly enough, its just the JWT verification thats the issue since disabling JWT auth for ONLYOFFICE allows it to work, but it not preferable for obvious reasons.

**Comment by AtriLahiji** [comment]
Heh... didn't change .htaccess.dist to .htaccess... Don't mind me...

**Comment by dreua** [comment]
Still an issue, should I create a new, more concise bug report about this?

**Comment by alexanderonlyoffice** [comment]
@dreua, we cannot reproduce the issue on our side. Could you please specify some additional information? 

1. Exact OS version of the server where your HumHub is installed;
2. Version of HumHub you are using;
3. Version of the ONLYOFFICE connector for HumHub;
4. Version of the Document Server; 
5. Specify also what exactly you changed in /etc/onlyoffice/documentserver/local.json;
6. Check also out.log in /var/log/onlyoffice/documentserver/converter/;
7. Check the accessibility of HumHub and Document Server in terminal via `wget https://humhub_address/` on the server with Document Server and `wget https://documentserver_address` on the server with HumHub.

**Comment by dreua** [comment]
1. CentOS Stream release 8 x86_64 
2. HumHub 1.9.1
3. OO-Connnector 2.2.2
4. Document Server (Docker image) 6.3.1.32
5. I haven't touched this file. (How could this be relevant to this issue?)
6. No entries in temporal relation to triggering this bug.
7. I really don't see the point of this check since it works as soon as I turn off HumHub's maintenance mode.

@alexanderonlyoffice Are you sure you put your HumHub in maintenance mode and tried editing a document? (I'm asking because it seems very reproducible to me, on two instances.)

**Comment by dreua** [comment]
Thank you, thisallows me to test OnlyOffice while in maintenance work and it should prevent some headaches to other administrators, too! :100:
