### ISSUE TITLE
Feature Request: deactivate SSL validation

### ISSUE THREAD

**Issue by marm1te** [ONLYOFFICE/onlyoffice-humhub#40]
Hi everybody,

you're integration of onlyOffice editor for humHub is nice. Thanks for that. Now we face a little issue regarding the ssl validation.

Case: Docker Image of only office (currently works only with self signed certificates):

Request:
Ability to deactivate ssl validation in the config.php of the onlyOffice module in HumHub.
eg.
[...
'validateSsl' => false
...]

**Comment by dreua** [comment]
I'd recommend to fix your SSL instead. In times of Let's encrypt I see no reason to not use proper SSL encryption. I have my oo-Docker behind a SSL terminating reverse proxy (Apache but Nginx should be fine, too), works like a charm and I don't have to deal with certificates within the Container.
If you really don't care, then don't use SSL at all. (Including HumHub. Not recommended for publicly accessible sites, of course, but for Testing that's always an option.)

**Comment by marm1te** [comment]
Hi there,
I agree with what you say. So you propose that I setup an nginx working as a reverse proxy and handle there the "letsencrypt" certificates for the container Port endpoints?

**Comment by marm1te** [comment]
Hey thanks for the kick :) . Just for the completeness of the dialogue. I used the nginx-proxy docker image from github and combined it with the acme-companion docker image from github as well. Quite well documented. That setup rocks now and is also compatible with multiple clients - adding each nearly automatically.
