### ISSUE TITLE
Humhub on port 443 and Document server on 80 not working

### ISSUE THREAD

**Issue by Ariel505** [ONLYOFFICE/onlyoffice-humhub#43]
Hi,
I seen some post regarding this issue but not yet found solution for my site.
I host my Humhub on port 443 with https through ssl 
installing onlyoffice Doc on port 80 and when I configure up the module in humhub with domain name but the documentserver is not accessible.
So link to Humhub: https://sure.hcu-hamburg.de
Link to Onlyoffice Doc: http://sure.hcu-hamburg.de (This is the link I gave in Hostname in module config)

Can someone tell me how to configure this correctly please?
Cheers,
Ariel

**Comment by dreua** [comment]
You must use https and port 443 for the onlyoffice document server as well (I'd recommend to use a different subdomain). The browser blocks non-https content on https, which is a good thing for security. I posted my configuration around here on different issues, the apache reverse proxy works well for me, but there are other solutions as well.

**Comment by SergeyKorneyev** [comment]
Hi @Ariel505 
The previous response from @dreua is absolutely correct: most browsers block mixed content pages (when an HTTPS page includes HTTP content), so you need to switch the Document Server to HTTPS in order for the integration to work.
