### ISSUE TITLE
Release Package 2.2.0 - Templates Missing

### ISSUE THREAD

**Issue by luke-** [ONLYOFFICE/onlyoffice-humhub#48]
In the ZIP just uploaded to Humhub Marketplace, the "templates" folder is missing.
 https://github.com/ONLYOFFICE/onlyoffice-humhub/tree/master/resources

It looks like this is now a Git submodule.

Can you please check.

**Comment by LinneyS** [comment]
Hi @luke- 
We have uploaded a new version. Thanks
