### ISSUE TITLE
Members in a Space cannot create new files despite permission

### ISSUE THREAD

**Issue by pheraph** [ONLYOFFICE/onlyoffice-humhub#95]
Members of a space cannot create new files (uploading, on the other hand, works), although the "Add files" right is permitted for members of the space:

![grafik](https://user-images.githubusercontent.com/58503/220319844-2ea86c10-3278-4d6d-846a-ed23d45dc739.png)

`TypeError: file is undefinedUpload.prototype.handleFileResponse@https://humhub.domain.tld/assets/40215d67/js/humhub.file.js?v=1675242337:270:13
init/ injectedScript:320:19r@https://humhub.domain.tld/assets/38e76184/js/browser/bluebird.min.js?v=1675242336:31:10952`

I am able to reliably reproduce the error on three different humhub instances.

### What steps will reproduce the problem?

Create a space, allow under Security/Permissions that members can create new files and deny that members can manage files. If, on the other hand, file management is allowed, members can create new files. However, the right "Add files" is described in such a way that this alone should be sufficient to create files: "Add files: Allows the user to upload new files and create folders"

This issue was first discussed as a core issue, but appears only with the OnlyOffice-module: https://github.com/humhub/humhub/issues/6120

**Comment by luke-** [comment]
@pheraph Please see my PR which should fixes the issue.

**Comment by pheraph** [comment]
Thanks, I can confirm your patch indeed fixes the issue! 👍

**Comment by pheraph** [comment]
I don't understand what has happened in the meantime, but the error occurs again in our test instances, i.e. as long as the person does not have the rights to manage files, the creation of a new file fails, even though the above patch has demonstrably been applied.

@luke- Any idea how I can help to isolate the problem?

**Comment by dreua** [comment]
Are your test instances really isolated? I once had an issue with mixed PHP caches, so beware of that in case you just have multiple installations on the same machine. (General HumHub issue, not related to onlyoffice)

**Comment by pheraph** [comment]
Thanks for the hint, but in that case the instances are totally unrelated on different machines.

**Comment by luke-** [comment]
@pheraph Is it exactly the same problem? Can you reproduce it everywhere or does it only occur on the "TEST" environments?
